# Week 8: Classification II

---
output:
  format:
  html:
toc: true
toc-location: right
toc-title: Contents
html-math-method: katex
css: styles.css
bibliography: references.bib
---

---
output:
  format:
  html:
toc: true
toc-location: right
toc-title: Contents
html-math-method: katex
css: styles.css
bibliography: references.bib
---

## Summary

### Object-Based Image Analysis (OBIA)

This involves pixels being grouped into objects based on similarity or difference of the cells. This group of pixels is also known as a **superpixel**, which can provide a condensed representation of images that can be useful for computationally demanding analysis.  

Simple Linear Iterative Clustering (SLIC) Algorithm is the most common method to generate superpixels. The algorithm produces superpixels by clustering pixels based on spatial proximity and colour similarity.

### Sub-Pixel Analysis

When we have a pixel that has a range of land cover classes within it, the challenge becomes whether we should calculate the proportions of each land cover class within the pixel or just classify it as one specific land cover class.

Sub-pixel analysis can help with this by separating pixels into sub-pixels to predict their landcover class labels by comparing the reflectance values of the sub-pixels to the values of a spectrally pure end member. By doing this, classification is conducted at a finer spatial resolution.

### Accuracy Assessment

We produce an accuracy assessment to determine how well the model performed in identifying different classes in unseen data.

In remote sensing, the most common form of accuracy assessment is to consider the producer's accuracy, user's accuracy, and overall accuracy, which are all derived from a confusion matrix. All measurements and equations to derive them are shown in the matrix below.

![From: [@ebrahimy2021]\]](accuracy_assessment_matrix.jpg)

**Kappa Coefficient:** evaluates how well the classification model performed compared to just assigning random values. Ranges from -1 to 1. It's use in remote sensing is discouraged, if using probably best to use last and with the support of other accuracy measures.

**F1:** Combines both user accuracy and producer accuracy. Ranges from 0 to 1 with 1 indicating better performance.

**Area Under the Receiver Operating Characteristic Curve (the ROC Curve):**

The curve plots the true positive and false positive rate. The AUC (area under the ROC curve) has a value between 0 and 1, with values closer to 1 having more accurate predictions.

![From: [@classifi]](roc_area.png){fig-align="center"}

**Cross Validation:** this trains the model on different subsets of the data. There are many different methods of cross validation.

### Spatial Cross Validation

When data is spatial, spatial autocorrelation can become a potential issue and impact the model. If we randomly split spatial data it can lead to training points being neighbours with testing points, leading to the test and training datasets not being independent which can lead to overfitting.

To avoid this, we can perform spatial cross validation which involves spatially partitioning the folded data.

## Applications

In this section I will focus on the applications of OBIA and sub-pixel analysis.

### **OBIA**

OBIA has been used extensively in land cover analysis, and is one of the most common methods for detecting informal settlements. This is because splitting up pixels into groups provides additional spectral, geometric and textural information [@kuffer2016] that are useful to detect specific structures that have unique characteristics in informal settlements, such as roofs of dwellings [@mudau2023] .

@fallatah2019 used OBIA to detect informal settlements in Jeddah, Saudi Arabia using Geoimage which offers high-resolution images. The study only looked at 3 smaller study areas within the city and started first by classifying objects into vegetation extent, housing structures, road networks, roofing materials, texture of built up areas and dwelling size before being able to identify and differentiate between formal and informal settlements. Upon further research, I found that OBIA works better on higher resolution images in comparison to lower resolution images [@hossain2019], which probably reflects the choice of remotely sensed data in the Jeddah study.

### Sub-Pixel Analysis

For sub-pixel analysis, I found that it has been used to detect changes in urban land-cover. Generally, change detection analysis is done on a per-pixel basis, however doing a sub-pixel analysis allows for the capture of changes that may be happening at a finer spatial resolution. One study used Landsat Thematic Mapper data and looked at the effectiveness of this method to detect land cover changes in the cities of Shangai and Xuzhou in China and found that the results were consistent with ground truth data [@du2014].

## Reflection

I found sub-pixel analysis really interesting as I already thought doing analysis on a pixel level was already pretty small! I think being able to distinguish between things that are smaller than a pixel will help to identify materials and surfaces that are often mixed in with others at that resolution, which will overall improve the accuracy of analysis. This being said, I can see how the accuracy of sub-pixel analysis would rely heavily on the quality of the input data, which is something that should be taken into consideration.

As I want to detect informal settlements as part of my dissertation, going over object based analysis was really useful and has helped me further understand the workflow behind such a methodology. Going over accuracy assessments for classification algorithms has also helped my thinking towards my dissertation as I will make sure to carefully consider the different assessments and their components. I also think it's useful in general to understand, because as I mentioned in last weeks reflection, the classification product will never be 100% accurate and so we should not take it at face value.

## References
